---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - /home/isaac/services/homer/data:/www/assets
      #- /home/isaac/services/homer/config:/www/config.yml
    ports:
      - 8092:8080
    environment:
      - UID=1000
      - GID=1000
